diccionario_palabras = [
    {"palabra": "Naruto", "categoria": "anime", "frase": "Un joven ninja con el sueño de convertirse en el líder de su aldea."},
    {"palabra": "Dragon Ball", "categoria": "anime", "frase": "Una serie de anime y manga que sigue las aventuras de Son Goku en su búsqueda de las esferas del dragón."},
    {"palabra": "One Piece", "categoria": "anime", "frase": "Una historia de piratas que sigue las aventuras de Monkey D. Luffy y su tripulación en busca del One Piece, el mayor tesoro del mundo."},
    {"palabra": "Death Note", "categoria": "anime", "frase": "Un estudiante de secundaria encuentra un cuaderno que le permite matar a cualquier persona cuyo nombre escriba en él."},
    {"palabra": "Attack on Titan", "categoria": "anime", "frase": "La humanidad lucha por sobrevivir contra gigantes humanoides devoradores de hombres conocidos como Titanes."},
    {"palabra": "My Hero Academia", "categoria": "anime", "frase": "Un joven sin poderes se une a una academia para entrenar y convertirse en un héroe."},
    {"palabra": "Tokyo Ghoul", "categoria": "anime", "frase": "Un estudiante universitario se convierte en mitad humano, mitad ghoul, y debe aprender a vivir en ambos mundos."},
    {"palabra": "Fullmetal Alchemist", "categoria": "anime", "frase": "Dos hermanos buscan la Piedra Filosofal para restaurar sus cuerpos después de un intento fallido de resucitar a su madre."},
    {"palabra": "Sword Art Online", "categoria": "anime", "frase": "Los jugadores quedan atrapados en un juego de realidad virtual donde la muerte en el juego significa la muerte en la vida real."},
    {"palabra": "Hunter x Hunter", "categoria": "anime", "frase": "Un joven aspirante a cazador se embarca en una búsqueda para encontrar a su padre y convertirse en un cazador."},
    {"palabra": "Demon Slayer", "categoria": "anime", "frase": "Un joven se une a una organización para cazar demonios y vengar la muerte de su familia."},
    {"palabra": "One Punch Man", "categoria": "anime", "frase": "Un héroe demasiado poderoso derrota a sus enemigos de un solo golpe y se aburre de la falta de desafíos."},
    {"palabra": "Neon Genesis Evangelion", "categoria": "anime", "frase": "Un grupo de adolescentes pilotea robots gigantes para proteger la Tierra de misteriosos seres conocidos como Ángeles."},
    {"palabra": "Fairy Tail", "categoria": "anime", "frase": "Un gremio de magos vive aventuras mientras realizan trabajos y luchan contra enemigos poderosos."},
    {"palabra": "Bleach", "categoria": "anime", "frase": "Un joven adquiere los poderes de un Shinigami y se embarca en la misión de proteger a los vivos y guiar a las almas perdidas."},
    {"palabra": "Naruto Shippuden", "categoria": "anime", "frase": "La continuación de la historia de Naruto Uzumaki mientras entrena para volverse más fuerte y proteger a sus seres queridos."},
    {"palabra": "Boruto", "categoria": "anime", "frase": "La historia sigue las aventuras de Boruto Uzumaki, hijo de Naruto, mientras lucha por encontrar su propio camino como ninja."},
    {"palabra": "Cowboy Bebop", "categoria": "anime", "frase": "Un grupo de cazarrecompensas viaja por el espacio en busca de criminales mientras lidian con su pasado y sus demonios internos."},
    {"palabra": "Black Clover", "categoria": "anime", "frase": "Un joven sin magia busca convertirse en el Rey Mago y proteger a su reino."},
    {"palabra": "Tokyo Revengers", "categoria": "anime", "frase": "Un estudiante se transporta en el tiempo y busca cambiar el futuro para evitar la muerte de su novia."},
    {"palabra": "Mob Psycho 100", "categoria": "anime", "frase": "Un estudiante con habilidades psíquicas trabaja como exorcista mientras intenta controlar sus poderes y encontrar su propósito en la vida."},
    {"palabra": "Promised Neverland", "categoria": "anime", "frase": "Un grupo de huérfanos descubre los oscuros secretos detrás de su orfanato y lucha por escapar de su destino."},
    {"palabra": "Code Geass", "categoria": "anime", "frase": "Un joven con el poder del Geass busca vengarse del Imperio Británico y crear un mundo mejor para su hermana."},
    {"palabra": "Dr. Stone", "categoria": "anime", "frase": "Después de que toda la humanidad se petrifica, un joven científico despierta y trabaja para reconstruir la civilización con la ciencia."},
    {"palabra": "Steins;Gate", "categoria": "anime", "frase": "Un grupo de amigos descubre una manera de enviar mensajes al pasado y se ven envueltos en una conspiración que amenaza el mundo."},
    {"palabra": "JoJo's Bizarre Adventure", "categoria": "anime", "frase": "Una saga épica que sigue a varias generaciones de la familia Joestar mientras luchan contra el mal en diferentes épocas y lugares."},
    {"palabra": "Re:Zero", "categoria": "anime", "frase": "Un chico es transportado a un mundo de fantasía y queda atrapado en un ciclo de muerte y resurrección."},
    {"palabra": "Fruits Basket", "categoria": "anime", "frase": "Una joven se muda con una familia que está maldita para transformarse en animales del zodíaco chino."},
    {"palabra": "Seven Deadly Sins", "categoria": "anime", "frase": "Un grupo de caballeros legendarios se reúne para derrotar al malvado grupo conocido como los Siete Pecados Capitales."},
    {"palabra": "Promare", "categoria": "anime", "frase": "En un mundo donde las personas tienen poderes de fuego, un equipo de bomberos lucha contra monstruos de fuego y una conspiración gubernamental."},
    {"palabra": "Soul Eater", "categoria": "anime", "frase": "Los estudiantes de la Academia Death Weapon Meister luchan contra seres malvados para convertir sus armas en Death Scythes."},
    {"palabra": "Made in Abyss", "categoria": "anime", "frase": "Una niña y un robot descienden al abismo para encontrar a la madre perdida de la niña y descubren horrores inimaginables en el camino."},
    {"palabra": "Bleach", "categoria": "anime", "frase": "Un joven adquiere los poderes de un Shinigami y se embarca en la misión de proteger a los vivos y guiar a las almas perdidas."},
    {"palabra": "Cardcaptor Sakura", "categoria": "anime", "frase": "Una niña encuentra cartas mágicas que deben ser capturadas para evitar que causen estragos en el mundo."},
    {"palabra": "Clannad", "categoria": "anime", "frase": "Un estudiante de secundaria conoce a una chica peculiar y juntos experimentan amor, amistad y tragedia."},
    {"palabra": "Claymore", "categoria": "anime", "frase": "Una organización de mujeres mitad humano, mitad monstruo lucha contra criaturas demoníacas conocidas como Yoma."},
    {"palabra": "Death Parade", "categoria": "anime", "frase": "Las almas de los muertos son juzgadas en un bar por juegos de azar mientras un misterioso arbitro decide su destino."},
    {"palabra": "Digimon", "categoria": "anime", "frase": "Un grupo de niños viaja a un mundo digital para salvarlo de la destrucción y aprender lecciones sobre la amistad y el coraje."},
    {"palabra": "Durarara!!", "categoria": "anime", "frase": "Una serie de eventos extraños y personajes excéntricos se entrelazan en los distritos de Ikebukuro, Tokio."},
    {"palabra": "Elfen Lied", "categoria": "anime", "frase": "Una joven con poderes de mutante escapa de un laboratorio y busca venganza contra la humanidad que la maltrató."},
    {"palabra": "Fairy Tail", "categoria": "anime", "frase": "Un gremio de magos vive aventuras mientras realizan trabajos y luchan contra enemigos poderosos."},
    {"palabra": "Fate/stay night", "categoria": "anime", "frase": "Un grupo de magos y héroes legendarios luchan por el Santo Grial y el deseo que puede conceder."},
    {"palabra": "Food Wars!", "categoria": "anime", "frase": "Un estudiante de cocina asiste a una academia culinaria de élite donde los duelos culinarios deciden el destino de los chefs."},
    {"palabra": "Fullmetal Alchemist", "categoria": "anime", "frase": "Dos hermanos buscan la Piedra Filosofal para restaurar sus cuerpos después de un intento fallido de resucitar a su madre."},
    {"palabra": "Gantz", "categoria": "anime", "frase": "Las personas recién fallecidas son resucitadas para luchar contra alienígenas en misiones peligrosas y mortales."},
    {"palabra": "Gurren Lagann", "categoria": "anime", "frase": "Un joven y su compañero descubren un mecha gigante y se embarcan en una misión para liberar a la humanidad de la opresión."},
    {"palabra": "High School DxD", "categoria": "anime", "frase": "Un estudiante es asesinado por un ángel y resucitado como demonio, y se une a un club de investigación paranormal."},
    {"palabra": "Inuyasha", "categoria": "anime", "frase": "Una adolescente viaja en el tiempo al Japón feudal y se une a un medio demonio en busca de fragmentos de la joya de cuatro almas."},
    {"palabra": "K-On!", "categoria": "anime", "frase": "Un grupo de chicas se une para formar un club de música en la escuela y se embarcan en aventuras musicales juntas."},
    {"palabra": "Kill la Kill", "categoria": "anime", "frase": "Una estudiante busca venganza por la muerte de su padre y lucha contra un sistema escolar autoritario con ropa que otorga poderes."},
    {"palabra": "Love Live!", "categoria": "anime", "frase": "Un grupo de chicas forma un grupo de ídolos para salvar su escuela de la bancarrota y competir en el Love Live! competencia."},
    {"palabra": "Magi: The Labyrinth of Magic", "categoria": "anime", "frase": "Un niño descubre un genio y se embarca en una aventura para conquistar mazmorras y cambiar el mundo."},
    {"palabra": "Mirai Nikki", "categoria": "anime", "frase": "Un estudiante recibe un diario que predice el futuro y se ve envuelto en un juego de supervivencia mortal."},
    {"palabra": "My Hero Academia", "categoria": "anime", "frase": "Un joven sin poderes se une a una academia para entrenar y convertirse en un héroe."},
    {"palabra": "Naruto", "categoria": "anime", "frase": "Un joven ninja con el sueño de convertirse en el líder de su aldea y ser reconocido por todos."},
    {"palabra": "No Game No Life", "categoria": "anime", "frase": "Dos hermanos genios son transportados a un mundo de juegos donde deben ganar para sobrevivir y reclamar el trono."},
    {"palabra": "Noragami", "categoria": "anime", "frase": "Un dios menor busca aumentar su número de seguidores y encuentra aventuras junto a una chica con un destino misterioso."},
    {"palabra": "One Punch Man", "categoria": "anime", "frase": "Un héroe demasiado poderoso derrota a sus enemigos de un solo golpe y se aburre de la falta de desafíos."},
    {"palabra": "Ouran High School Host Club", "categoria": "anime", "frase": "Una chica sin recursos se une a un club de chicos ricos y guapos y se embarca en hilarantes aventuras románticas."},
    {"palabra": "Overlord", "categoria": "anime", "frase": "Un jugador queda atrapado en un juego de realidad virtual y se convierte en un gobernante temido en un mundo de fantasía."},
    {"palabra": "Puella Magi Madoka Magica", "categoria": "anime", "frase": "Una chica es reclutada por un gato mágico para convertirse en una chica mágica y luchar contra brujas que amenazan el mundo."},
    {"palabra": "Rurouni Kenshin", "categoria": "anime", "frase": "Un ex asesino busca redención por sus pecados y protege a los inocentes como un samurái errante."},
    {"palabra": "Shingeki no Kyojin", "categoria": "anime", "frase": "La humanidad lucha por sobrevivir contra gigantes humanoides devoradores de hombres conocidos como Titanes."},
    {"palabra": "Soul Eater", "categoria": "anime", "frase": "Los estudiantes de la Academia Death Weapon Meister luchan contra seres malvados para convertir sus armas en Death Scythes."},
    {"palabra": "Sword Art Online", "categoria": "anime", "frase": "Los jugadores quedan atrapados en un juego de realidad virtual donde la muerte en el juego significa la muerte en la vida real."},
    {"palabra": "Tokyo Ghoul", "categoria": "anime", "frase": "Un estudiante universitario se convierte en mitad humano, mitad ghoul, y debe aprender a vivir en ambos mundos."},
    {"palabra": "Toradora!", "categoria": "anime", "frase": "Dos estudiantes de secundaria con personalidades opuestas forman una inesperada amistad y romance."},
    {"palabra": "Trigun", "categoria": "anime", "frase": "Un pistolero pacifista viaja por el desierto y se enfrenta a su oscuro pasado mientras busca aventuras y justicia."},
    {"palabra": "Violet Evergarden", "categoria": "anime", "frase": "Una ex soldado se convierte en escritora de cartas para comprender el significado del amor y la emoción humana."},
    {"palabra": "Yu Yu Hakusho", "categoria": "anime", "frase": "Un adolescente es revivido como un detective espiritual y lucha contra demonios y monstruos en nombre del mundo de los vivos."},
    {"palabra": "Zankyou no Terror", "categoria": "anime", "frase": "Dos jóvenes terroristas planean una serie de ataques en Tokio como venganza por los experimentos que sufrieron en su infancia."},
    {"palabra": "Bakuman", "categoria": "anime", "frase": "Dos amigos de la infancia se unen para crear manga y alcanzar el éxito en el mundo editorial."},
    {"palabra": "Hellsing", "categoria": "anime", "frase": "Un grupo de cazadores de vampiros lucha contra fuerzas sobrenaturales y amenazas demoníacas."},
    {"palabra": "Serial Experiments Lain", "categoria": "anime", "frase": "Una chica se sumerge en un mundo virtual y se encuentra enredada en una conspiración que desafía la realidad misma."},
    {"palabra": "Akame ga Kill!", "categoria": "anime", "frase": "Un grupo de asesinos lucha contra un gobierno corrupto y poderoso en un mundo de traición y violencia."},
    {"palabra": "Black Butler", "categoria": "anime", "frase": "Un demonio sirviente y su amo humano realizan tareas para la reina de Inglaterra mientras investigan conspiraciones sobrenaturales."},
    {"palabra": "Parasyte", "categoria": "anime", "frase": "Los seres humanos son invadidos por parásitos alienígenas que se apoderan de sus cuerpos y buscan sobrevivir en un mundo hostil."},
    {"palabra": "Angel Beats!", "categoria": "anime", "frase": "Un grupo de estudiantes muertos se encuentra en un limbo escolar y lucha contra sus problemas pasados y su destino incierto."},
    {"palabra": "Fate/Zero", "categoria": "anime", "frase": "Los magos convocan héroes legendarios para luchar en una batalla real por el Santo Grial y el deseo que puede conceder."},
    {"palabra": "Psycho-Pass", "categoria": "anime", "frase": "En un futuro distópico, la policía utiliza un sistema de vigilancia para predecir y prevenir el crimen antes de que ocurra."},
    {"titulo": "El Padrino", "genero": "Drama", "sinopsis": "La historia de la familia Corleone, líderes de la mafia italiana en Nueva York."},
    {"titulo": "Forrest Gump", "genero": "Drama", "sinopsis": "La vida de Forrest Gump, un hombre con una discapacidad intelectual, quien vive una serie de eventos importantes en la historia de Estados Unidos."},
    {"titulo": "Titanic", "genero": "Romance", "sinopsis": "El hundimiento del famoso barco Titanic y el romance entre dos pasajeros de diferentes clases sociales."},
    {"titulo": "El Señor de los Anillos: El Retorno del Rey", "genero": "Fantasía", "sinopsis": "La última parte de la trilogía épica que sigue la búsqueda para destruir el Anillo Único y derrotar al Señor Oscuro Sauron."},
    {"titulo": "La Lista de Schindler", "genero": "Drama", "sinopsis": "La historia real de Oskar Schindler, un empresario alemán que salvó a más de mil judíos durante el Holocausto."},
    {"titulo": "La Guerra de las Galaxias (Star Wars)", "genero": "Ciencia ficción", "sinopsis": "La lucha entre el bien y el mal en una galaxia muy, muy lejana, donde los Jedi luchan contra el Imperio Galáctico."},
    {"titulo": "Matrix", "genero": "Ciencia ficción", "sinopsis": "Un hacker descubre la verdad sobre la realidad y se une a una rebelión contra las máquinas que controlan la humanidad."},
    {"titulo": "El Rey León", "genero": "Animación", "sinopsis": "La historia de Simba, un joven león que lucha por reclamar su lugar como rey de la selva después de la muerte de su padre."},
    {"titulo": "Salvar al Soldado Ryan", "genero": "Bélico", "sinopsis": "Un grupo de soldados es enviado detrás de las líneas enemigas durante la Segunda Guerra Mundial para rescatar a un soldado cuyos hermanos han muerto en combate."},
    {"titulo": "Gladiador", "genero": "Drama", "sinopsis": "La historia de Maximus, un general romano que se convierte en esclavo y lucha en la arena para vengar la muerte de su familia y recuperar su honor."},
    {"titulo": "Interestelar", "genero": "Ciencia ficción", "sinopsis": "Un grupo de astronautas viaja a través de un agujero de gusano en busca de un nuevo hogar para la humanidad."},
    {"titulo": "El Gran Hotel Budapest", "genero": "Comedia", "sinopsis": "Las aventuras de un conserje y un botones en un famoso hotel europeo entre las dos guerras mundiales."},
    {"titulo": "El Resplandor", "genero": "Terror", "sinopsis": "Un hombre acepta un trabajo como cuidador de un hotel durante el invierno, pero la soledad y la locura comienzan a afectar su cordura."},
    {"titulo": "Pulp Fiction", "genero": "Crimen", "sinopsis": "Una serie de historias interconectadas sobre criminales, drogas y redención en Los Ángeles."},
    {"titulo": "El Club de la Lucha", "genero": "Drama", "sinopsis": "Un hombre descontento con su vida se une a un club clandestino donde hombres luchan entre sí como una forma de escape."},
    {"titulo": "Regreso al Futuro", "genero": "Ciencia ficción", "sinopsis": "Un adolescente viaja en el tiempo en un DeLorean modificado y accidentalmente cambia el curso de la historia de su familia."},
    {"titulo": "La La Land", "genero": "Musical", "sinopsis": "La historia de amor entre un pianista y una aspirante a actriz en la ciudad de Los Ángeles."},
    {"titulo": "Toy Story", "genero": "Animación", "sinopsis": "La vida de los juguetes cobra vida cuando no hay humanos cerca, y un vaquero de juguete se enfrenta a un nuevo juguete espacial por el afecto de su dueño."},
    {"titulo": "Jurassic Park", "genero": "Aventura", "sinopsis": "Un parque temático con dinosaurios reales se convierte en una pesadilla cuando los animales escapan y comienzan a cazar a los humanos."},
    {"titulo": "El Caballero de la Noche (The Dark Knight)", "genero": "Superhéroes", "sinopsis": "Batman se enfrenta al Joker, un villano psicópata que amenaza con sumir a Gotham City en el caos."},
    {"titulo": "El Sexto Sentido", "genero": "Suspenso", "sinopsis": "Un niño que puede ver y comunicarse con los muertos se encuentra ayudando a un psicólogo infantil atormentado."},
    {"titulo": "Matrix", "genero": "Ciencia ficción", "sinopsis": "Un hacker descubre la verdad sobre la realidad y se une a una rebelión contra las máquinas que controlan la humanidad."},
    {"titulo": "El Gran Hotel Budapest", "genero": "Comedia", "sinopsis": "Las aventuras de un conserje y un botones en un famoso hotel europeo entre las dos guerras mundiales."},
    {"titulo": "El Resplandor", "genero": "Terror", "sinopsis": "Un hombre acepta un trabajo como cuidador de un hotel durante el invierno, pero la soledad y la locura comienzan a afectar su cordura."},
    {"titulo": "Pulp Fiction", "genero": "Crimen", "sinopsis": "Una serie de historias interconectadas sobre criminales, drogas y redención en Los Ángeles."},
    {"titulo": "El Club de la Lucha", "genero": "Drama", "sinopsis": "Un hombre descontento con su vida se une a un club clandestino donde hombres luchan entre sí como una forma de escape."},
    {"titulo": "Regreso al Futuro", "genero": "Ciencia ficción", "sinopsis": "Un adolescente viaja en el tiempo en un DeLorean modificado y accidentalmente cambia el curso de la historia de su familia."},
    {"titulo": "La La Land", "genero": "Musical", "sinopsis": "La historia de amor entre un pianista y una aspirante a actriz en la ciudad de Los Ángeles."},
    {"titulo": "Toy Story", "genero": "Animación", "sinopsis": "La vida de los juguetes cobra vida cuando no hay humanos cerca, y un vaquero de juguete se enfrenta a un nuevo juguete espacial por el afecto de su dueño."},
    {"titulo": "Jurassic Park", "genero": "Aventura", "sinopsis": "Un parque temático con dinosaurios reales se convierte en una pesadilla cuando los animales escapan y comienzan a cazar a los humanos."},
    {"titulo": "El Caballero de la Noche (The Dark Knight)", "genero": "Superhéroes", "sinopsis": "Batman se enfrenta al Joker, un villano psicópata que amenaza con sumir a Gotham City en el caos."},
    {"titulo": "El Sexto Sentido", "genero": "Suspenso", "sinopsis": "Un niño que puede ver y comunicarse con los muertos se encuentra ayudando a un psicólogo infantil atormentado."},
    {"titulo": "El Laberinto del Fauno", "genero": "Fantasía", "sinopsis": "Una niña española escapa a un mundo de fantasía durante la posguerra civil española, donde encuentra a una criatura mágica y se enfrenta a un malvado capitán militar."},
    {"titulo": "Ciudad de Dios", "genero": "Drama", "sinopsis": "La vida en las favelas de Río de Janeiro, Brasil, y el ascenso de un joven delincuente a un poderoso jefe del crimen."},
    {"titulo": "La Vida es Bella", "genero": "Drama", "sinopsis": "Un hombre utiliza su ingenio y humor para proteger a su hijo mientras están en un campo de concentración nazi."},
    {"titulo": "El Silencio de los Corderos", "genero": "Suspenso", "sinopsis": "Una joven agente del FBI busca la ayuda de un brillante pero psicótico asesino en serie para atrapar a otro asesino en serie que está aterrorizando a la ciudad."},
    {"titulo": "El Bueno, el Malo y el Feo", "genero": "Western", "sinopsis": "Tres pistoleros buscan un tesoro escondido durante la Guerra Civil estadounidense."},
    {"titulo": "Amélie", "genero": "Comedia", "sinopsis": "La historia de Amélie, una joven camarera en París que decide mejorar la vida de quienes la rodean mientras busca el amor verdadero."},
    {"titulo": "La Naranja Mecánica", "genero": "Ciencia ficción", "sinopsis": "En un futuro distópico, un joven delincuente es sometido a un tratamiento de modificación de la conducta para rehabilitarlo, pero las cosas no salen según lo planeado."},
    {"titulo": "El Gran Lebowski", "genero": "Comedia", "sinopsis": "Las desventuras de un hombre llamado 'El Nota' después de que se confunde con un millonario del mismo nombre."},
    {"titulo": "El Ciudadano Kane", "genero": "Drama", "sinopsis": "La historia de un magnate de los medios de comunicación y las complejidades de su vida y carrera."},
    {"titulo": "Blade Runner", "genero": "Ciencia ficción", "sinopsis": "En un futuro distópico, un detective cazador de replicantes busca y retira androides rebeldes en Los Ángeles."},
    {"titulo": "El Rescate del Soldado Ryan", "genero": "Bélico", "sinopsis": "Un grupo de soldados es enviado detrás de las líneas enemigas durante la Segunda Guerra Mundial para rescatar a un soldado cuyos hermanos han muerto en combate."},
    {"titulo": "El Padrino", "genero": "Drama", "sinopsis": "La historia de la familia Corleone, líderes de la mafia italiana en Nueva York."},
    {"titulo": "Forrest Gump", "genero": "Drama", "sinopsis": "La vida de Forrest Gump, un hombre con una discapacidad intelectual, quien vive una serie de eventos importantes en la historia de Estados Unidos."},
    {"titulo": "Titanic", "genero": "Romance", "sinopsis": "El hundimiento del famoso barco Titanic y el romance entre dos pasajeros de diferentes clases sociales."},
    {"titulo": "El Señor de los Anillos: El Retorno del Rey", "genero": "Fantasía", "sinopsis": "La última parte de la trilogía épica que sigue la búsqueda para destruir el Anillo Único y derrotar al Señor Oscuro Sauron."},
    {"titulo": "La Lista de Schindler", "genero": "Drama", "sinopsis": "La historia real de Oskar Schindler, un empresario alemán que salvó a más de mil judíos durante el Holocausto."},
    {"titulo": "La Guerra de las Galaxias (Star Wars)", "genero": "Ciencia ficción", "sinopsis": "La lucha entre el bien y el mal en una galaxia muy, muy lejana, donde los Jedi luchan contra el Imperio Galáctico."},
    {"titulo": "Matrix", "genero": "Ciencia ficción", "sinopsis": "Un hacker descubre la verdad sobre la realidad y se une a una rebelión contra las máquinas que controlan la humanidad."},
    {"titulo": "El Rey León", "genero": "Animación", "sinopsis": "La historia de Simba, un joven león que lucha por reclamar su lugar como rey de la selva después de la muerte de su padre."},
    {"titulo": "Salvar al Soldado Ryan", "genero": "Bélico", "sinopsis": "Un grupo de soldados es enviado detrás de las líneas enemigas durante la Segunda Guerra Mundial para rescatar a un soldado cuyos hermanos han muerto en combate."},
    {"titulo": "Apocalypse Now", "genero": "Bélico", "sinopsis": "Un capitán del ejército es enviado en una misión para asesinar a un coronel renegado durante la Guerra de Vietnam."},
    {"titulo": "Pulp Fiction", "genero": "Crimen", "sinopsis": "Varias historias entrelazadas sobre criminales, gánsteres y boxeadores en Los Ángeles."},
    {"titulo": "El Club de la Pelea", "genero": "Drama", "sinopsis": "Un hombre insomne y un vendedor de jabón crean un club de lucha clandestino que se convierte en algo mucho más grande."},
    {"titulo": "Tiempos Violentos", "genero": "Crimen", "sinopsis": "Un par de matones, un boxeador en decadencia y una esposa infiel se cruzan en Los Ángeles."},
    {"titulo": "Matrix", "genero": "Ciencia ficción", "sinopsis": "Un hacker descubre la verdad sobre la realidad y se une a una rebelión contra las máquinas que controlan la humanidad."},
    {"titulo": "El Exorcista", "genero": "Terror", "sinopsis": "Una niña es poseída por un demonio y dos sacerdotes intentan salvarla a través de un exorcismo."},
    {"titulo": "El Resplandor", "genero": "Terror", "sinopsis": "Un hombre acepta un trabajo como cuidador de un hotel durante el invierno y se vuelve loco mientras está aislado con su familia."},
    {"titulo": "Psicosis", "genero": "Terror", "sinopsis": "Una secretaria roba dinero de su jefe y se refugia en un motel dirigido por un hombre atormentado por su madre."},
    {"titulo": "Cadena Perpetua", "genero": "Drama", "sinopsis": "Un hombre es condenado por el asesinato de su esposa y su amante, pero insiste en su inocencia durante décadas en prisión."},
    {"titulo": "El Mago de Oz", "genero": "Fantasía", "sinopsis": "Una joven llamada Dorothy es transportada a la tierra de Oz, donde debe seguir el camino de baldosas amarillas para regresar a casa."},
    {"titulo": "El Rey León", "genero": "Animación", "sinopsis": "La historia de Simba, un joven león que lucha por reclamar su lugar como rey de la selva después de la muerte de su padre."},
    {"titulo": "Regreso al Futuro", "genero": "Ciencia ficción", "sinopsis": "Un adolescente viaja en el tiempo en un DeLorean modificado y debe asegurarse de que sus padres se enamoren para salvar su futuro."},
    {"titulo": "El Gran Dictador", "genero": "Comedia", "sinopsis": "Un barbero judío es confundido con un dictador parecido a Hitler y aprovecha la oportunidad para dar un discurso sobre la libertad y la igualdad."},
    {"titulo": "El Rey León", "genero": "Animación", "sinopsis": "La historia de Simba, un joven león que lucha por reclamar su lugar como rey de la selva después de la muerte de su padre."},
    {"titulo": "Taxi Driver", "genero": "Drama", "sinopsis": "Un veterano de Vietnam se convierte en un taxista nocturno en Nueva York y se sumerge en la violencia de la ciudad."},
    {"titulo": "La Sociedad de los Poetas Muertos", "genero": "Drama", "sinopsis": "Un profesor de literatura inspira a sus estudiantes a vivir vidas auténticas y desafiar las expectativas de la sociedad."},
    {"titulo": "Volver al Futuro", "genero": "Ciencia ficción", "sinopsis": "Un adolescente viaja en el tiempo en un DeLorean modificado y debe asegurarse de que sus padres se enamoren para salvar su futuro."},
    {"titulo": "Los Cazafantasmas", "genero": "Comedia", "sinopsis": "Un equipo de cazadores de fantasmas lucha contra entidades sobrenaturales en Nueva York."},
    {"titulo": "El Gran Hotel Budapest", "genero": "Comedia", "sinopsis": "Las aventuras del conserje de un elegante hotel europeo y su joven protegido durante la época de entreguerras."},
    {"titulo": "El Padrino II", "genero": "Drama", "sinopsis": "La historia continúa con la familia Corleone, explorando el pasado de Vito Corleone y el ascenso de su hijo Michael al poder."},
    {"titulo": "El Regreso del Jedi", "genero": "Ciencia ficción", "sinopsis": "La última parte de la trilogía original de Star Wars, donde la Rebelión se enfrenta al Imperio en la batalla final por la galaxia."},
    {"titulo": "Raiders of the Lost Ark", "genero": "Aventura", "sinopsis": "El arqueólogo y aventurero Indiana Jones se embarca en una misión para encontrar el Arca de la Alianza antes que los nazis."},
    {"titulo": "La Bella y la Bestia", "genero": "Animación", "sinopsis": "Una joven llamada Bella se ofrece como prisionera en lugar de su padre y se encuentra con una bestia encantada en un castillo."},
    {"titulo": "La Forma del Agua", "genero": "Fantasía", "sinopsis": "Una mujer de limpieza muda se enamora de una criatura anfibia mantenida en un laboratorio gubernamental durante la Guerra Fría."},
    {"titulo": "Harry Potter y la Piedra Filosofal", "genero": "Fantasía", "sinopsis": "La primera parte de la saga de Harry Potter, donde el joven mago descubre su verdadera identidad y comienza su educación en Hogwarts."},
    {"titulo": "El Gran Gatsby", "genero": "Drama", "sinopsis": "La historia de Jay Gatsby, un millonario misterioso obsesionado con una mujer llamada Daisy Buchanan durante la década de 1920 en Long Island."},
    {"titulo": "El Show de Truman", "genero": "Drama", "sinopsis": "La vida de Truman Burbank, quien descubre que su vida entera ha sido un reality show transmitido las 24 horas del día."},
    {"titulo": "El Silencio de los Corderos", "genero": "Suspenso", "sinopsis": "Una joven agente del FBI busca la ayuda de un brillante pero peligroso psiquiatra encarcelado para atrapar a un asesino en serie conocido como Buffalo Bill."},
    {"titulo": "Forrest Gump", "genero": "Drama", "sinopsis": "La vida de Forrest Gump, un hombre con un coeficiente intelectual bajo que se encuentra en el centro de eventos importantes en la historia de Estados Unidos."},
    {"titulo": "El Señor de los Anillos: La Comunidad del Anillo", "genero": "Fantasía", "sinopsis": "La primera parte de la trilogía épica que sigue la búsqueda para destruir el Anillo Único y derrotar al Señor Oscuro Sauron."},
    {"titulo": "El Rey León", "genero": "Animación", "sinopsis": "La historia de Simba, un joven león que lucha por reclamar su lugar como rey de la selva después de la muerte de su padre."},
    {"titulo": "El Padrino", "genero": "Drama", "sinopsis": "La saga de la familia Corleone, una poderosa dinastía criminal italiana en Nueva York, liderada por el patriarca Don Vito Corleone."},
    {"titulo": "El Laberinto del Fauno", "genero": "Fantasía", "sinopsis": "Durante la posguerra española, una niña escapa a un mundo mágico donde se enfrenta a criaturas místicas y un malvado capitán militar."},
    {"titulo": "Interestelar", "genero": "Ciencia ficción", "sinopsis": "Un grupo de exploradores viaja a través de un agujero de gusano en busca de un nuevo hogar para la humanidad después de que la Tierra se vuelva inhabitable."},
    {"titulo": "La Lista de Schindler", "genero": "Drama", "sinopsis": "La verdadera historia de Oskar Schindler, un empresario alemán que salvó a más de mil judíos durante el Holocausto al emplearlos en su fábrica."},
    {"titulo": "La La Land", "genero": "Musical", "sinopsis": "La historia de amor entre un pianista de jazz y una aspirante a actriz en Los Ángeles, mientras persiguen sus sueños en la industria del entretenimiento."},
    {"titulo": "Toy Story", "genero": "Animación", "sinopsis": "La primera película de Pixar que sigue las aventuras de Woody, un vaquero de juguete, y Buzz Lightyear, un astronauta del espacio, mientras intentan regresar a casa después de ser separados de su dueño, Andy."},
    {"titulo": "El Origen", "genero": "Ciencia ficción", "sinopsis": "Un ladrón especializado en robar secretos corporativos a través de la infiltración en el subconsciente de sus objetivos es contratado para implantar una idea en la mente de un CEO rival."},
    {"titulo": "Titanic", "genero": "Drama", "sinopsis": "La historia de amor entre Jack y Rose, dos pasajeros a bordo del RMS Titanic, que se conocen y enamoran durante el trágico viaje inaugural del famoso transatlántico."},
    {"titulo": "El Sexto Sentido", "genero": "Suspenso", "sinopsis": "Un niño que ve gente muerta busca la ayuda de un psicólogo infantil para lidiar con su don sobrenatural, mientras descubre un oscuro secreto sobre su terapeuta."},
    {"titulo": "Memento", "genero": "Suspenso", "sinopsis": "Un hombre con amnesia anterógrada busca vengarse del asesino de su esposa, utilizando fotos instantáneas y tatuajes para recordar detalles importantes de su investigación."},
    {"titulo": "El Gran Showman", "genero": "Musical", "sinopsis": "La historia de P.T. Barnum, el famoso empresario circense que fundó el circo más grande y famoso del mundo, Barnum & Bailey Circus."},
    {"titulo": "Origen", "genero": "Ciencia ficción", "sinopsis": "Un ladrón especializado en robar secretos corporativos a través de la infiltración en el subconsciente de sus objetivos es contratado para implantar una idea en la mente de un CEO rival."},
    {"titulo": "El Planeta de los Simios", "genero": "Ciencia ficción", "sinopsis": "Un grupo de astronautas aterriza en un planeta habitado por simios inteligentes y descubre un mundo donde los humanos son esclavos y los simios dominan."},
    {"titulo": "El Rey León", "genero": "Animación", "sinopsis": "La historia de Simba, un joven león que lucha por reclamar su lugar como rey de la selva después de la muerte de su padre."},
    {"titulo": "La Novia Cadáver", "genero": "Animación", "sinopsis": "Un hombre se casa accidentalmente con el cadáver de una novia mientras practicaba sus votos de boda en el bosque, y es llevado al mundo de los muertos donde se encuentra con su verdadero amor."},
    {"titulo": "El Rey León", "genero": "Animación", "sinopsis": "La historia de Simba, un joven león que lucha por reclamar su lugar como rey de la selva después de la muerte de su padre."},
    {"titulo": "El Silencio de los Inocentes", "genero": "Suspenso", "sinopsis": "Una joven agente del FBI busca la ayuda de un brillante pero peligroso psiquiatra encarcelado para atrapar a un asesino en serie conocido como Buffalo Bill."},
    {"titulo": "La Vida es Bella", "genero": "Drama", "sinopsis": "La historia de un hombre judío italiano y su familia durante el Holocausto, donde usa su ingenio y humor para proteger a su hijo del horror del campo de concentración."},
    {"titulo": "El Hombre Araña", "genero": "Superhéroes", "sinopsis": "Un estudiante de secundaria es mordido por una araña radiactiva y adquiere superpoderes, convirtiéndose en el superhéroe conocido como Spider-Man."},
    {"palabra": "Stranger Things", "categoria": "ciencia ficción", "frase": "Un grupo de amigos se enfrenta a eventos paranormales en su pequeño pueblo."},
    {"palabra": "The Mandalorian", "categoria": "ciencia ficción", "frase": "Un cazarrecompensas mandaloriano viaja por la galaxia en una época turbulenta."},
    {"palabra": "Breaking Bad", "categoria": "drama", "frase": "Un profesor de química con cáncer comienza a producir y vender metanfetamina para asegurar el futuro de su familia."},
    {"palabra": "Game of Thrones", "categoria": "fantasía", "frase": "Varias familias nobles luchan por el control del Trono de Hierro en un mundo de fantasía."},
    {"palabra": "The Crown", "categoria": "drama histórico", "frase": "Un retrato de la vida de la reina Isabel II de Inglaterra y su reinado."},
    {"palabra": "La Casa de Papel", "categoria": "drama", "frase": "Un grupo de atracadores lleva a cabo un plan para asaltar la Fábrica Nacional de Moneda y Timbre."},
    {"palabra": "Dark", "categoria": "ciencia ficción", "frase": "Un pueblo alemán se ve envuelto en un misterio que involucra viajes en el tiempo y desapariciones inexplicables."},
    {"palabra": "The Witcher", "categoria": "fantasía", "frase": "Un cazador de monstruos conocido como Geralt de Rivia viaja por el continente en busca de su lugar en el mundo."},
    {"palabra": "Peaky Blinders", "categoria": "drama histórico", "frase": "Una familia de gánsteres de Birmingham, Inglaterra, se enfrenta a sus rivales y a la policía en la década de 1920."},
    {"palabra": "Black Mirror", "categoria": "ciencia ficción", "frase": "Una serie de historias independientes que exploran los lados oscuros de la tecnología y su impacto en la sociedad."},
    {"palabra": "The Boys", "categoria": "superhéroes", "frase": "Un grupo de vigilantes se enfrenta a un grupo de superhéroes corruptos que abusan de sus poderes."},
    {"palabra": "Ozark", "categoria": "drama", "frase": "Un asesor financiero se ve envuelto en un cartel mexicano de la droga."},
    {"palabra": "Mindhunter", "categoria": "drama", "frase": "Dos agentes del FBI entrevistan a asesinos en serie para comprender mejor sus motivaciones."},
    {"palabra": "The Handmaid's Tale", "categoria": "distopía", "frase": "En un futuro distópico, una mujer es obligada a ser concubina de un comandante en una sociedad totalitaria."},
    {"palabra": "Westworld", "categoria": "ciencia ficción", "frase": "Un parque temático de robots con conciencia de sí mismos comienza a desafiar las reglas de su programación."},
    {"palabra": "Better Call Saul", "categoria": "drama", "frase": "La historia de cómo un abogado mediocre se convirtió en el infame Saul Goodman de Breaking Bad."},
    {"palabra": "Succession", "categoria": "drama", "frase": "Un magnate de los medios de comunicación y su familia disfuncional luchan por el control de su imperio."},
    {"palabra": "Chernobyl", "categoria": "drama histórico", "frase": "Un minucioso relato del accidente nuclear de Chernobyl en 1986."},
    {"palabra": "Fleabag", "categoria": "comedia", "frase": "Una joven ingeniosa y sarcástica navega por las dificultades de la vida moderna en Londres."},
    {"palabra": "Barry", "categoria": "comedia", "frase": "Un asesino a sueldo decide dejar su vida de crimen para convertirse en actor."},
    {"palabra": "The Good Place", "categoria": "comedia", "frase": "Una mujer que ha vivido una vida egoísta muere y va al cielo por error."},
    {"palabra": "BoJack Horseman", "categoria": "comedia dramática", "frase": "Un caballo antropomórfico que es una ex estrella de televisión lucha contra la depresión y la adicción."},
    {"palabra": "Rick y Morty", "categoria": "comedia animada", "frase": "Un científico loco y su nieto Morty se embarcan en aventuras interdimensionales."},
    {"palabra": "South Park", "categoria": "comedia animada", "frase": "Un grupo de niños traviesos viven en un pequeño pueblo de Colorado."},
    {"palabra": "Los Simpson", "categoria": "comedia animada", "frase": "Una familia disfuncional de Springfield vive situaciones cómicas y satíricas."},
    {"palabra": "Family Guy", "categoria": "comedia animada", "frase": "Una familia disfuncional de Rhode Island vive situaciones cómicas y surrealistas."},
    {"palabra": "American Dad", "categoria": "comedia animada", "frase": "Un agente de la CIA y su familia disfuncional viven situaciones cómicas y satíricas."},
    {"palabra": "BoJack Horseman", "categoria": "comedia dramática", "frase": "Un caballo antropomórfico que es una ex estrella de televisión lucha contra la depresión y la adicción."},
    {"palabra": "The Office", "categoria": "comedia", "frase": "Un grupo de empleados de oficina viven situaciones cómicas y cotidianas."},
    {"palabra": "Friends", "categoria": "comedia", "frase": "Un grupo de amigos viven en la ciudad de Nueva York y experimentan las dificultades y alegrías de la vida adulta."},
    {"palabra": "Seinfeld", "categoria": "comedia", "frase": "Un comediante y sus amigos viven situaciones cómicas en la ciudad de Nueva York."},
    {"palabra": "The Big Bang Theory", "categoria": "comedia", "frase": "Un grupo de científicos nerds viven situaciones cómicas y románticas en Pasadena, California."},
    {"palabra": "How I Met Your Mother", "categoria": "comedia", "frase": "Un hombre le cuenta a sus hijos cómo conoció a su madre en la ciudad de Nueva York."},
    {"palabra": "Modern Family", "categoria": "comedia", "frase": "Tres familias con diferentes estilos de vida viven situaciones cómicas y cotidianas."},
    {"palabra": "The Office (UK)", "categoria": "comedia", "frase": "Un grupo de empleados de oficina viven situaciones cómicas y cotidianas en una pequeña oficina en Slough, Inglaterra."},
    {"palabra": "Parks and Recreation", "categoria": "comedia", "frase": "Un grupo de empleados del gobierno local de una pequeña ciudad de Indiana viven situaciones cómicas y cotidianas."},
    {"palabra": "Community", "categoria": "comedia", "frase": "Un grupo de estudiantes de un colegio comunitario viven situaciones cómicas y estrambóticas."},
    {"palabra": "Arrested Development", "categoria": "comedia", "frase": "Una familia disfuncional de millonarios que ha perdido su fortuna trata de adaptarse a su nueva vida."},
    {"palabra": "30 Rock", "categoria": "comedia", "frase": "Un grupo de guionistas y actores de un programa de televisión de sketches viven situaciones cómicas y caóticas."},
    {"palabra": "Veep", "categoria": "comedia", "frase": "La vicepresidenta de los Estados Unidos y su equipo de trabajo viven situaciones cómicas y satíricas."},
    {"palabra": "Silicon Valley", "categoria": "comedia", "frase": "Un grupo de jóvenes emprendedores intentan triunfar en el mundo de la tecnología en Silicon Valley."},
    {"palabra": "Curb Your Enthusiasm", "categoria": "comedia", "frase": "Un comediante semi-retirado vive situaciones cómicas y conflictivas en su vida diaria."},
    {"palabra": "It's Always Sunny in Philadelphia", "categoria": "comedia", "frase": "Un grupo de amigos que son dueños de un bar en Filadelfia viven situaciones cómicas y ofensivas."},
    {"palabra": "Seinfeld", "categoria": "comedia", "frase": "Un comediante y sus amigos viven situaciones cómicas en la ciudad de Nueva York."},
    {"palabra": "The Big Bang Theory", "categoria": "comedia", "frase": "Un grupo de científicos nerds viven situaciones cómicas y románticas en Pasadena, California."},
    {"palabra": "How I Met Your Mother", "categoria": "comedia", "frase": "Un hombre le cuenta a sus hijos cómo conoció a su madre en la ciudad de Nueva York."},
    {"palabra": "Modern Family", "categoria": "comedia", "frase": "Tres familias con diferentes estilos de vida viven situaciones cómicas y cotidianas."},
    {"palabra": "The Office (UK)", "categoria": "comedia", "frase": "Un grupo de empleados de oficina viven situaciones cómicas y cotidianas en una pequeña oficina en Slough, Inglaterra."},
    {"palabra": "Parks and Recreation", "categoria": "comedia", "frase": "Un grupo de empleados del gobierno local de una pequeña ciudad de Indiana viven situaciones cómicas y cotidianas."},
    {"palabra": "Community", "categoria": "comedia", "frase": "Un grupo de estudiantes de un colegio comunitario viven situaciones cómicas y estrambóticas."},
    {"palabra": "Arrested Development", "categoria": "comedia", "frase": "Una familia disfuncional de millonarios que ha perdido su fortuna trata de adaptarse a su nueva vida."},
    {"palabra": "30 Rock", "categoria": "comedia", "frase": "Un grupo de guionistas y actores de un programa de televisión de sketches viven situaciones cómicas y caóticas."},
    {"palabra": "Veep", "categoria": "comedia", "frase": "La vicepresidenta de los Estados Unidos y su equipo de trabajo viven situaciones cómicas y satíricas."},
    {"palabra": "Silicon Valley", "categoria": "comedia", "frase": "Un grupo de jóvenes emprendedores intentan triunfar en el mundo de la tecnología en Silicon Valley."},
    {"palabra": "Curb Your Enthusiasm", "categoria": "comedia", "frase": "Un comediante semi-retirado vive situaciones cómicas y conflictivas en su vida diaria."},
    {"palabra": "It's Always Sunny in Philadelphia", "categoria": "comedia", "frase": "Un grupo de amigos que son dueños de un bar en Filadelfia viven situaciones cómicas y ofensivas."},
    {"palabra": "The Simpsons", "categoria": "comedia animada", "frase": "Una familia disfuncional de Springfield vive situaciones cómicas y satíricas."},
    {"palabra": "Family Guy", "categoria": "comedia animada", "frase": "Una familia disfuncional de Rhode Island vive situaciones cómicas y surrealistas."},
    {"palabra": "American Dad", "categoria": "comedia animada", "frase": "Un agente de la CIA y su familia disfuncional viven situaciones cómicas y satíricas."},
    {"palabra": "South Park", "categoria": "comedia animada", "frase": "Un grupo de niños traviesos viven en un pequeño pueblo de Colorado."},
    {"palabra": "Rick y Morty", "categoria": "comedia animada", "frase": "Un científico loco y su nieto Morty se embarcan en aventuras interdimensionales."},
    {"palabra": "Bob's Burgers", "categoria": "comedia animada", "frase": "Una familia que regenta una hamburguesería vive situaciones cómicas y cotidianas."},
    {"palabra": "Archer", "categoria": "comedia animada", "frase": "Un agente secreto egocéntrico y disfuncional lidera un equipo de espías incompetentes."},
    {"palabra": "Futurama", "categoria": "comedia animada", "frase": "Un repartidor de pizzas del siglo XX es congelado y despierta en el año 2999."},
    {"palabra": "American Horror Story", "categoria": "serie de antología de terror", "frase": "Cada temporada de la serie presenta una historia independiente con diferentes personajes y escenarios."},
    {"palabra": "Black Mirror", "categoria": "ciencia ficción", "frase": "Una serie de historias independientes que exploran los lados oscuros de la tecnología y su impacto en la sociedad."},
    {"palabra": "The Twilight Zone", "categoria": "serie de antología de ciencia ficción y fantasía", "frase": "Cada episodio presenta una historia independiente que explora temas como la moralidad, la tecnología y la naturaleza humana."},
    {"palabra": "True Detective", "categoria": "serie de antología de misterio", "frase": "Cada temporada de la serie presenta una historia independiente con diferentes personajes y escenarios, y se centra en la investigación de un crimen complejo."},
    {"palabra": "Fargo", "categoria": "serie de antología de crimen", "frase": "Cada temporada de la serie presenta una historia independiente con diferentes personajes y escenarios, inspirada en la película homónima de los hermanos Coen."},
    {"palabra": "American Crime Story", "categoria": "serie de antología de crimen", "frase": "Cada temporada de la serie presenta una historia independiente basada en un caso criminal real."},
    {"palabra": "Genius", "categoria": "serie de antología biográfica", "frase": "Cada temporada de la serie presenta la vida de un personaje histórico diferente."},
    {"palabra": "The Crown", "categoria": "drama histórico", "frase": "Un retrato de la vida de la reina Isabel II de Inglaterra y su reinado."},
    {"palabra": "Downton Abbey", "categoria": "drama histórico", "frase": "La vida de una familia aristocrática inglesa y sus sirvientes a principios del siglo XX."},
    {"palabra": "Mad Men", "categoria": "drama histórico", "frase": "La vida de los empleados de una agencia de publicidad en la ciudad de Nueva York en la década de 1960."},
    {"palabra": "The Sopranos", "categoria": "drama", "frase": "La vida de un jefe de la mafia de Nueva Jersey que lucha por conciliar su vida familiar y criminal."},
    {"palabra": "The Wire", "categoria": "drama", "frase": "Un retrato crudo y realista de la vida en las calles de Baltimore, Maryland."},
    {"palabra": "Breaking Bad", "categoria": "drama", "frase": "Un profesor de química con cáncer comienza a producir y vender metanfetamina para asegurar el futuro de su familia."},
    {"palabra": "Game of Thrones", "categoria": "fantasía", "frase": "Varias familias nobles luchan por el control del Trono de Hierro en un mundo de fantasía."},
    {"palabra": "The Walking Dead", "categoria": "serie de terror", "frase": "Un grupo de supervivientes de un apocalipsis zombi lucha por sobrevivir en un mundo hostil."},
    {"palabra": "Stranger Things", "categoria": "ciencia ficción", "frase": "Un grupo de amigos se enfrenta a eventos paranormales en su pequeño pueblo."},
    {"palabra": "The Mandalorian", "categoria": "ciencia ficción", "frase": "Un cazarrecompensas mandaloriano viaja por la galaxia en una época turbulenta."},
    {"palabra": "The Witcher", "categoria": "fantasía", "frase": "Un cazador de monstruos conocido como Geralt de Rivia viaja por el continente en busca de su lugar en el mundo."},
    {"palabra": "Peaky Blinders", "categoria": "drama histórico", "frase": "Una familia de gánsteres de Birmingham, Inglaterra, se enfrenta a sus rivales y a la policía en la década de 1920."},
    {"palabra": "Ozark", "categoria": "drama", "frase": "Un asesor financiero se ve envuelto en un cartel mexicano de la droga."},
    {"palabra": "Mindhunter", "categoria": "drama", "frase": "Dos agentes del FBI entrevistan a asesinos en serie para comprender mejor sus motivaciones."},
    {"palabra": "The Handmaid's Tale", "categoria": "distopía", "frase": "En un futuro distópico, una mujer es obligada a ser concubina de un comandante en una sociedad totalitaria."},
    {"palabra": "Westworld", "categoria": "ciencia ficción", "frase": "Un parque temático de robots con conciencia de sí mismos comienza a desafiar las reglas de su programación."},
    {"palabra": "Better Call Saul", "categoria": "drama", "frase": "La historia de cómo un abogado mediocre se convirtió en el infame Saul Goodman de Breaking Bad."},
    {"palabra": "Succession", "categoria": "drama", "frase": "Un magnate de los medios de comunicación y su familia disfuncional luchan por el control de su imperio."},
    {"palabra": "Chernobyl", "categoria": "drama histórico", "frase": "Un minucioso relato del accidente nuclear de Chernobyl en 1986."},
    {"palabra": "Fleabag", "categoria": "comedia", "frase": "Una joven ingeniosa y sarcástica navega por las dificultades de la vida moderna en Londres."},
    {"palabra": "Barry", "categoria": "comedia", "frase": "Un asesino a sueldo decide dejar su vida de crimen para convertirse en actor."},
    {"palabra": "The Good Place", "categoria": "comedia", "frase": "Una mujer que ha vivido una vida egoísta muere y va al cielo por error."},
    {"palabra": "BoJack Horseman", "categoria": "comedia dramática", "frase": "Un caballo antropomórfico que es una ex estrella de televisión lucha contra la depresión y la adicción."},
    {"palabra": "Russian Doll", "categoria": "comedia dramática", "frase": "Una mujer revive el mismo día una y otra vez, atrapada en un bucle temporal."},
    {"palabra": "Fleabag", "categoria": "comedia", "frase": "Una joven ingeniosa y sarcástica navega por las dificultades de la vida moderna en Londres."},
    {"palabra": "Succession", "categoria": "drama", "frase": "Un magnate de los medios de comunicación y su familia disfuncional luchan por el control de su imperio."},
    {"palabra": "Watchmen", "categoria": "serie de superhéroes", "frase": "Un grupo de vigilantes enmascarados se enfrenta a una sociedad que los considera criminales."},
    {"palabra": "The Boys", "categoria": "serie de superhéroes", "frase": "Un grupo de vigilantes se enfrenta a un grupo de superhéroes corruptos que abusan de sus poderes."},
    {"palabra": "Fútbol", "categoria": "deporte", "frase": "Un deporte de equipo que se juega con un balón entre dos equipos de once jugadores."},
    {"palabra": "Baloncesto", "categoria": "deporte", "frase": "Un deporte de equipo que se juega en una cancha rectangular con aros en cada extremo, donde los jugadores intentan anotar puntos lanzando un balón a través del aro del equipo contrario."},
    {"palabra": "Tenis", "categoria": "deporte", "frase": "Un deporte de raqueta que se juega entre dos personas (individuales) o dos parejas (dobles), donde los jugadores golpean una pelota de un lado a otro de una red, usando raquetas."},
    {"palabra": "Atletismo", "categoria": "deporte", "frase": "Una colección de disciplinas deportivas que incluyen carreras, saltos y lanzamientos, que se practican individualmente o en equipos."},
    {"palabra": "Natación", "categoria": "deporte", "frase": "Un deporte acuático en el que los participantes nadan y compiten en diferentes estilos y distancias en piscinas, aguas abiertas o en el mar."},
    {"palabra": "Golf", "categoria": "deporte", "frase": "Un deporte en el que los jugadores intentan golpear una pelota en hoyos en el menor número de golpes posible, utilizando una variedad de palos en un campo de golf."},
    {"palabra": "Rugby", "categoria": "deporte", "frase": "Un deporte de equipo similar al fútbol americano, en el que los jugadores intentan llevar el balón hasta la zona de anotación del equipo contrario, mediante pases hacia atrás o patadas."},
    {"palabra": "Ciclismo", "categoria": "deporte", "frase": "Un deporte que implica montar en bicicleta y que incluye diferentes disciplinas como ciclismo de ruta, ciclismo de montaña, ciclismo de pista y ciclismo de BMX."},
    {"palabra": "Boxeo", "categoria": "deporte", "frase": "Un deporte de combate en el que dos personas luchan entre sí usando únicamente sus puños, con el objetivo de derrotar al oponente mediante nocaut o puntos."},
    {"palabra": "Voleibol", "categoria": "deporte", "frase": "Un deporte de equipo en el que dos equipos compiten para pasar un balón por encima de una red y hacerlo tocar el suelo en el campo contrario."},
    {"palabra": "Hockey", "categoria": "deporte", "frase": "Un deporte de equipo en el que los jugadores utilizan palos curvos para golpear una pelota y marcar goles en la portería del equipo contrario."},
    {"palabra": "Escalada", "categoria": "deporte", "frase": "Un deporte que implica escalar paredes de roca, montañas o estructuras artificiales utilizando manos, pies y equipo especializado, con el objetivo de alcanzar la cima."},
    {"palabra": "Surf", "categoria": "deporte", "frase": "Un deporte acuático en el que los participantes surfean en la cresta de las olas utilizando tablas especiales, buscando realizar maniobras y mantener el equilibrio sobre la tabla."},
    {"palabra": "Esquí", "categoria": "deporte", "frase": "Un deporte de invierno en el que los participantes deslizan sobre la nieve utilizando esquís, ya sea en pistas preparadas, fuera de pista o en terreno alpino."},
    {"palabra": "Béisbol", "categoria": "deporte", "frase": "Un deporte de equipo en el que dos equipos compiten para golpear una pelota con un bate y correr alrededor de una serie de bases para anotar carreras."},
    {"palabra": "Carrera", "categoria": "deporte", "frase": "Una competición en la que los participantes corren a pie para llegar primero a la meta, en distancias que van desde cortas hasta maratones."},
    {"palabra": "Gimnasia", "categoria": "deporte", "frase": "Un deporte que incluye una variedad de disciplinas que requieren fuerza, flexibilidad, equilibrio y control del cuerpo, como la gimnasia artística, la gimnasia rítmica y la gimnasia aeróbica."},
    {"palabra": "Artes marciales", "categoria": "deporte", "frase": "Un conjunto de disciplinas físicas y mentales que incluyen técnicas de combate, autodefensa y desarrollo personal, como el karate, judo, taekwondo, kung fu y jiu-jitsu."},
    {"palabra": "Ajedrez", "categoria": "deporte", "frase": "Un juego de estrategia que se juega en un tablero con 64 casillas y con piezas blancas y negras, donde los jugadores buscan capturar al rey del oponente mientras protegen el suyo."},
    {"palabra": "Cricket", "categoria": "deporte", "frase": "Un deporte de equipo que se juega con un bate y una pelota en un campo ovalado, donde un equipo batea mientras el otro equipo lanza y busca eliminar a los bateadores y evitar que anoten carreras."},
    {"palabra": "Triatlón", "categoria": "deporte", "frase": "Una competición multideportiva que consiste en tres disciplinas consecutivas: natación, ciclismo y carrera a pie, en distancias variables según la modalidad."},
    {"palabra": "Salto en paracaídas", "categoria": "deporte", "frase": "Una actividad en la que una persona se lanza desde una altura considerable con un paracaídas para descender al suelo de forma controlada y segura."},
    {"palabra": "Equitación", "categoria": "deporte", "frase": "Un deporte que implica montar a caballo y participar en diversas disciplinas como doma clásica, salto ecuestre, y concurso completo de equitación, entre otras."},
    {"palabra": "Patinaje", "categoria": "deporte", "frase": "Una actividad que consiste en desplazarse sobre una superficie con patines, ya sea sobre hielo o ruedas, practicando diversas modalidades como patinaje artístico, velocidad o hockey sobre patines."},
    {"palabra": "Skateboarding", "categoria": "deporte", "frase": "Un deporte en el que el participante utiliza una tabla con ruedas para realizar acrobacias y maniobras en pistas o en la calle, destacando el estilo libre y el skatepark."},
    {"palabra": "Snowboarding", "categoria": "deporte", "frase": "Un deporte de invierno que consiste en descender pendientes nevadas utilizando una tabla similar a la del surf, practicando diferentes modalidades como freestyle, freeride o alpino."},
    {"palabra": "Yoga", "categoria": "deporte", "frase": "Una práctica física, mental y espiritual originaria de la India que incluye posturas físicas, ejercicios de respiración y meditación, buscando el equilibrio y la armonía del cuerpo y la mente."},
    {"palabra": "Pilates", "categoria": "deporte", "frase": "Un sistema de ejercicios físicos que se centra en fortalecer los músculos centrales del cuerpo, mejorar la postura y la flexibilidad mediante movimientos controlados y precisos."},
    {"palabra": "Pesca", "categoria": "deporte", "frase": "Una actividad recreativa y deportiva que consiste en atrapar peces utilizando diferentes técnicas, como la pesca con caña, la pesca submarina o la pesca con mosca."},
    {"palabra": "Caza", "categoria": "deporte", "frase": "Una actividad deportiva y de ocio que implica la búsqueda y persecución de animales salvajes con fines deportivos, de conservación o alimentación, utilizando armas como rifles o arcos."},
    {"palabra": "Remo", "categoria": "deporte", "frase": "Un deporte acuático en el que los participantes utilizan remos para propulsar una embarcación, ya sea en aguas tranquilas (remo olímpico) o en aguas turbulentas (remo de mar)."},
    {"palabra": "Piragüismo", "categoria": "deporte", "frase": "Un deporte acuático que consiste en navegar en una embarcación ligera de uno, dos o cuatro tripulantes, utilizando una pala de doble hoja para propulsarse, compitiendo en diferentes modalidades como sprint o eslalon."},
    {"palabra": "Motocross", "categoria": "deporte", "frase": "Una disciplina del deporte del motor que se practica en circuitos off-road con motocicletas especialmente diseñadas, realizando saltos y acrobacias en terrenos accidentados y embarrados."},
    {"palabra": "Automovilismo", "categoria": "deporte", "frase": "Un deporte de motor que implica competir en carreras de automóviles en circuitos cerrados o en tramos de carretera, en diversas modalidades como Fórmula 1, rally, NASCAR o resistencia."},
    {"palabra": "Rally", "categoria": "deporte", "frase": "Una competición de automovilismo que se disputa en carreteras abiertas, caminos de tierra y pistas forestales, donde los pilotos recorren largas distancias en etapas cronometradas, superando obstáculos y terrenos variados."},
    {"palabra": "Vela", "categoria": "deporte", "frase": "Un deporte náutico que consiste en navegar utilizando el viento como fuerza motriz, controlando la dirección y la velocidad de una embarcación con velas, compitiendo en diferentes clases y modalidades."},
    {"palabra": "Windsurf", "categoria": "deporte", "frase": "Una disciplina que combina elementos del surf y la vela, donde los participantes se desplazan sobre una tabla con una vela adherida, aprovechando el viento para deslizarse sobre el agua y realizar acrobacias."},
    {"palabra": "Kitesurf", "categoria": "deporte", "frase": "Un deporte acuático que consiste en deslizarse sobre el agua utilizando una tabla similar a la del surf y un cometa (kite) que se controla con una barra, permitiendo realizar saltos y maniobras sobre las olas."},
    {"palabra": "Esgrima", "categoria": "deporte", "frase": "Un deporte de combate en el que dos contrincantes se enfrentan utilizando armas blancas, como espadas, floretes o sables, con el objetivo de tocar al oponente sin ser tocado."},
    {"palabra": "Tiro con arco", "categoria": "deporte", "frase": "Una disciplina en la que los participantes utilizan un arco y flechas para disparar a blancos fijos o móviles, puntuando según la precisión y la distancia alcanzada."},
    {"palabra": "Bádminton", "categoria": "deporte", "frase": "Un deporte de raqueta en el que dos jugadores o parejas se enfrentan golpeando un volante (pluma o shuttle) con raquetas, sobre una red dividida en dos campos."},
    {"palabra": "Squash", "categoria": "deporte", "frase": "Un deporte de raqueta que se juega en una pista cerrada, donde dos jugadores golpean una pelota de goma con raquetas, intentando que el oponente no la devuelva."},
    {"palabra": "Raquetbol", "categoria": "deporte", "frase": "Un deporte de raqueta similar al squash, que se juega en una pista cerrada con raquetas y pelotas de goma, buscando que la pelota rebote en las paredes para ganar puntos."},
    {"palabra": "Polo", "categoria": "deporte", "frase": "Un deporte ecuestre de equipo en el que dos equipos montados a caballo intentan golpear una pelota de plástico con un mazo largo para marcar goles en una portería contraria."},
    {"palabra": "Polo acuático", "categoria": "deporte", "frase": "Un deporte acuático de equipo que se juega en una piscina, donde dos equipos intentan marcar goles lanzando una pelota con la mano o con la cabeza, nadando y utilizando flotadores para desplazarse."},
    {"palabra": "Waterpolo", "categoria": "deporte", "frase": "Una variante del polo acuático que se juega en una piscina profunda, donde los jugadores nadan y se pasan una pelota para intentar marcar goles en la portería contraria."},
    {"palabra": "Lucha libre", "categoria": "deporte", "frase": "Un deporte de combate en el que dos luchadores se enfrentan utilizando técnicas de agarre, derribo y sumisión, buscando inmovilizar al oponente o hacerlo rendir."},
    {"palabra": "Halterofilia", "categoria": "deporte", "frase": "Un deporte en el que los participantes levantan pesas en dos movimientos específicos: el arrancada y el envión, compitiendo por levantar la mayor cantidad de peso en cada uno."},
    {"palabra": "Levantamiento de pesas", "categoria": "deporte", "frase": "Un deporte en el que los atletas levantan pesas en dos movimientos: el arrancada y el envión, compitiendo por levantar la mayor cantidad de peso posible en cada uno."},
    {"palabra": "Powerlifting", "categoria": "deporte", "frase": "Una disciplina de levantamiento de pesas que se centra en tres movimientos principales: sentadillas, press de banca y peso muerto, buscando levantar la mayor cantidad de peso posible en cada uno."},
    {"palabra": "CrossFit", "categoria": "deporte", "frase": "Un programa de entrenamiento físico que combina diferentes modalidades y ejercicios funcionales de alta intensidad, como levantamiento de pesas, gimnasia, carrera y ejercicios cardiovasculares, buscando mejorar la resistencia, la fuerza y la condición física general."},
    {"palabra": "Patinaje artístico", "categoria": "deporte", "frase": "Una disciplina del patinaje sobre hielo en la que los patinadores realizan rutinas coreografiadas que combinan saltos, piruetas y movimientos elegantes y expresivos, buscando impresionar a los jueces con su técnica y gracia."},
    {"palabra": "Patinaje de velocidad", "categoria": "deporte", "frase": "Una modalidad del patinaje sobre hielo en la que los patinadores compiten por completar una pista ovalada lo más rápido posible, alcanzando velocidades muy altas gracias a la técnica y el impulso."},
    {"palabra": "Patinaje sobre hielo", "categoria": "deporte", "frase": "Una actividad recreativa y deportiva que se practica deslizándose sobre una superficie de hielo utilizando patines, realizando piruetas, giros y saltos, tanto en competiciones como en sesiones de ocio."},
    {"palabra": "Patinaje sobre ruedas", "categoria": "deporte", "frase": "Una actividad que se practica deslizándose sobre una superficie lisa utilizando patines de ruedas, ya sea en pistas especiales, calles o parques, compitiendo en diferentes modalidades como velocidad, roller derby o patinaje artístico."},
    {"palabra": "Escalada en hielo", "categoria": "deporte", "frase": "Una disciplina de escalada en la que los escaladores suben por formaciones de hielo natural o artificial, utilizando crampones y piolets para asegurarse y avanzar en terrenos escarpados y helados."},
    {"palabra": "Escalada en roca", "categoria": "deporte", "frase": "Un deporte en el que los escaladores suben por paredes de roca natural o artificial, utilizando manos y pies para buscar agarres y encontrar rutas desafiantes, compitiendo en diferentes modalidades como boulder, escalada deportiva o escalada alpina."},
    {"palabra": "Parkour", "categoria": "deporte", "frase": "Una disciplina física que consiste en desplazarse de forma eficiente y rápida por diferentes entornos urbanos o naturales, superando obstáculos y realizando movimientos acrobáticos y saltos, buscando fluidez y creatividad en el movimiento."},
    {"palabra": "Calistenia", "categoria": "deporte", "frase": "Un tipo de entrenamiento físico que utiliza el peso corporal como resistencia, realizando ejercicios como flexiones, dominadas, fondos y abdominales para desarrollar fuerza, resistencia y flexibilidad."},
    {"palabra": "Triatlón", "categoria": "deporte", "frase": "Una competición de resistencia que combina tres disciplinas: natación, ciclismo y carrera a pie, en la que los participantes compiten por completar las distancias establecidas en el menor tiempo posible."},
    {"palabra": "Ironman", "categoria": "deporte", "frase": "Una de las competiciones de triatlón más exigentes, que consiste en nadar 3.86 km, recorrer en bicicleta 180.25 km y correr una maratón de 42.2 km, sin interrupción y en un tiempo limitado."},
    {"palabra": "Maratón", "categoria": "deporte", "frase": "Una carrera de larga distancia que cubre una distancia de 42.195 kilómetros, inspirada en la leyenda de Filípides, quien se dice que corrió desde Maratón hasta Atenas para anunciar la victoria sobre los persas."},
    {"palabra": "Medio maratón", "categoria": "deporte", "frase": "Una carrera de resistencia que cubre una distancia de 21.0975 kilómetros, la mitad de la distancia de un maratón estándar, desafiando a los corredores con un recorrido exigente pero más corto que un maratón completo."},
    {"palabra": "Ultramaratón", "categoria": "deporte", "frase": "Una carrera de resistencia que cubre distancias más largas que un maratón estándar, generalmente de 50 kilómetros o más, desafiando a los corredores con terrenos variados y condiciones extremas."},
    {"palabra": "Marcha atlética", "categoria": "deporte", "frase": "Una modalidad atlética en la que los participantes caminan largas distancias con una técnica específica que implica mantener siempre un pie en contacto con el suelo, compitiendo por completar la distancia en el menor tiempo posible sin correr."},
    {"palabra": "Carrera de obstáculos", "categoria": "deporte", "frase": "Una competición en la que los participantes deben superar una serie de obstáculos físicos y mentales, como muros, zanjas, escaladas y arrastres, compitiendo por completar el recorrido en el menor tiempo posible."},
    {"palabra": "Biatlón", "categoria": "deporte", "frase": "Una competición de resistencia que combina dos disciplinas: esquí de fondo y tiro con rifle, en la que los participantes compiten por completar las distancias de esquí y disparar a blancos específicos en el menor tiempo posible."},
    {"palabra": "Pentatlón moderno", "categoria": "deporte", "frase": "Una competición que combina cinco disciplinas: esgrima, natación, equitación, tiro con pistola y carrera a pie, inspirada en las habilidades necesarias para un soldado en tiempos de guerra, compitiendo por acumular la mayor cantidad de puntos en todas las disciplinas."},
    {"palabra": "Decatlón", "categoria": "deporte", "frase": "Una competición de atletismo que consta de diez pruebas diferentes realizadas durante dos días: 100 metros, salto de longitud, lanzamiento de peso, salto de altura, 400 metros, 110 metros vallas, lanzamiento de disco, salto con pértiga, lanzamiento de jabalina y 1500 metros."},
    {"palabra": "Heptatlón", "categoria": "deporte", "frase": "Una competición de atletismo femenino que consta de siete pruebas realizadas durante dos días: 100 metros vallas, salto de altura, lanzamiento de peso, 200 metros, salto de longitud, lanzamiento de jabalina y 800 metros."},
    {"palabra": "Duatlón", "categoria": "deporte", "frase": "Una competición de resistencia que combina dos disciplinas: carrera a pie y ciclismo, en la que los participantes compiten por completar las distancias de carrera y ciclismo en el menor tiempo posible."},
    {"palabra": "Trail running", "categoria": "deporte", "frase": "Una modalidad de carrera a pie que se realiza en senderos naturales, montañas y terrenos agrestes, desafiando a los corredores con ascensos, descensos y terrenos irregulares, en busca de aventura y contacto con la naturaleza."},
    {"palabra": "Esquí de fondo", "categoria": "deporte", "frase": "Un deporte de invierno que se practica deslizándose sobre nieve con esquíes, recorriendo largas distancias en terrenos planos o ligeramente inclinados, utilizando la técnica de patinaje o de estilo clásico."},
    {"palabra": "Esquí alpino", "categoria": "deporte", "frase": "Una disciplina del esquí que se practica en pistas preparadas y marcadas, con descensos rápidos y giros cerrados, compitiendo en diferentes modalidades como slalom, eslalon gigante, supergigante y descenso."},
    {"palabra": "Esquí acuático", "categoria": "deporte", "frase": "Un deporte acuático en el que los participantes esquían sobre el agua agarrados a una cuerda, arrastrados por una lancha a motor, realizando acrobacias y giros en el agua."},
    {"palabra": "Esquí de montaña", "categoria": "deporte", "frase": "Una actividad que consiste en recorrer terrenos nevados y montañosos utilizando esquíes para ascender y descender, explorando entornos naturales y remotas fuera de las pistas de esquí convencionales."},
    {"palabra": "Esquí de travesía", "categoria": "deporte", "frase": "Una modalidad del esquí de montaña que consiste en ascender y descender montañas utilizando esquíes de travesía y pieles de foca para adherirse a la nieve en las subidas, explorando terrenos remotos y fuera de las áreas de esquí convencionales."},
    {"palabra": "Snowboard freestyle", "categoria": "deporte", "frase": "Una modalidad del snowboard que se practica en snowparks y halfpipes, realizando acrobacias, saltos y trucos sobre la tabla, buscando la creatividad y la expresión personal en el manejo de la tabla sobre la nieve."},
    {"palabra": "Snowboard alpino", "categoria": "deporte", "frase": "Una disciplina del snowboard que se practica en pendientes empinadas y preparadas, con carreras cronometradas y giros cerrados, compitiendo en diferentes modalidades como slalom gigante y slalom paralelo."},
    {"palabra": "Snowboard cross", "categoria": "deporte", "frase": "Una modalidad del snowboard que se practica en un recorrido con obstáculos y saltos, compitiendo varios corredores al mismo tiempo en una carrera de descenso rápido, sorteando obstáculos y buscando llegar primero a la meta."},
    {"palabra": "Snowboard halfpipe", "categoria": "deporte", "frase": "Una modalidad del snowboard que se practica en una pista en forma de U con paredes laterales, realizando acrobacias y trucos en el aire mientras se desliza de un lado a otro del halfpipe."},
    {"palabra": "Snowboard slopestyle", "categoria": "deporte", "frase": "Una modalidad del snowboard que se practica en un recorrido con una variedad de obstáculos como rails, cajas y saltos, realizando acrobacias y trucos en cada elemento del recorrido para obtener la mejor puntuación."},
    {"palabra": "Kayak", "categoria": "deporte", "frase": "Una embarcación pequeña y estrecha propulsada por una pala de doble hoja, utilizada para navegar en aguas tranquilas y rápidas, practicando diferentes disciplinas como el kayak de aguas bravas, el kayak de travesía y el kayak de mar."},
    {"palabra": "Canoa", "categoria": "deporte", "frase": "Una embarcación larga y estrecha propulsada por una pala de una sola hoja, utilizada para navegar en aguas tranquilas y rápidas, compitiendo en diferentes modalidades como la canoa slalom, la canoa sprint y el descenso en aguas bravas."},
    {"palabra": "Slalom", "categoria": "deporte", "frase": "Una disciplina acuática que consiste en navegar por un recorrido con puertas colocadas en el agua, sorteando los obstáculos y realizando giros cerrados para completar el trayecto en el menor tiempo posible."},
    {"palabra": "Descenso", "categoria": "deporte", "frase": "Una modalidad del piragüismo y el kayakismo que consiste en descender por aguas rápidas y turbulentas, sorteando rocas, rápidos y obstáculos naturales, compitiendo en diferentes categorías según la dificultad del recorrido."},
    {"palabra": "Maratón acuático", "categoria": "deporte", "frase": "Una disciplina de natación en aguas abiertas que consiste en nadar largas distancias en aguas naturales como ríos, lagos u océanos, compitiendo en eventos de larga distancia que pueden alcanzar varios kilómetros."},
    {"palabra": "Natación sincronizada", "categoria": "deporte", "frase": "Una disciplina acuática que combina natación, danza y gimnasia, realizando rutinas sincronizadas en el agua al ritmo de la música, coordinando movimientos corporales y acrobacias en equipo."},
    {"palabra": "Waterpolo", "categoria": "deporte", "frase": "Un deporte acuático de equipo que se juega en una piscina, donde dos equipos compiten por marcar goles en la portería del oponente utilizando una pelota y nadando estratégicamente."},
    {"palabra": "Saltos ornamentales", "categoria": "deporte", "frase": "Una disciplina acuática que implica realizar una serie de saltos desde una plataforma elevada o un trampolín, ejecutando acrobacias y figuras en el aire antes de entrar al agua con precisión y gracia."},
    {"palabra": "Polo acuático", "categoria": "deporte", "frase": "Un deporte de equipo que se juega en una piscina, donde dos equipos montados en flotadores compiten por marcar goles en la portería del oponente utilizando una pelota y estrategias tácticas."},
    {"palabra": "Windsurf", "categoria": "deporte", "frase": "Un deporte acuático que combina el surf y la navegación a vela, donde el deportista se desplaza sobre una tabla de windsurf impulsada por una vela, utilizando el viento para navegar y realizar maniobras."},
    {"palabra": "Kitesurf", "categoria": "deporte", "frase": "Un deporte acuático que combina el surf y el vuelo de cometas, donde el deportista se desplaza sobre una tabla de kitesurf impulsada por una cometa controlada con una barra, utilizando el viento para navegar y realizar acrobacias."},
    {"palabra": "Surf de remo", "categoria": "deporte", "frase": "Una modalidad del surf que implica remar sobre una tabla de surf más grande con una paleta, utilizando el remo para desplazarse en el agua y atrapar olas para surfearlas de pie o arrodillado."},
    {"palabra": "Bodyboard", "categoria": "deporte", "frase": "Una modalidad del surf que implica deslizarse sobre una tabla de bodyboard o boogie board, acostado sobre el abdomen, utilizando los brazos y las piernas para dirigir la tabla y surfear las olas."},
    {"palabra": "Skimboard", "categoria": "deporte", "frase": "Un deporte acuático que implica deslizarse sobre una tabla delgada y plana (skimboard) sobre la superficie del agua, lanzándola desde la orilla y corriendo para saltar sobre ella y deslizarse en la orilla de las olas."},
    {"palabra": "Longboard", "categoria": "deporte", "frase": "Una modalidad del surf que implica surfear olas con una tabla de longboard, más larga y ancha que las tablas de surf tradicionales, permitiendo realizar maniobras más suaves y fluidas."},
    {"palabra": "Paddleboarding", "categoria": "deporte", "frase": "Un deporte acuático que implica remar de pie sobre una tabla de paddleboard utilizando una paleta, practicado en aguas tranquilas como lagos, ríos y océanos para el ejercicio, la recreación y la exploración."},
    {"palabra": "Perro", "categoria": "animal", "frase": "Un fiel compañero del ser humano, conocido por su lealtad y diversidad de razas."},
    {"palabra": "Gato", "categoria": "animal", "frase": "Un felino doméstico de comportamiento independiente y elegante."},
    {"palabra": "Elefante", "categoria": "animal", "frase": "Un mamífero terrestre de gran tamaño, reconocido por su trompa y colmillos largos."},
    {"palabra": "León", "categoria": "animal", "frase": "Un majestuoso felino que habita en las llanuras africanas, conocido por su melena distintiva y su comportamiento depredador en la caza."},
    {"palabra": "Tigre", "categoria": "animal", "frase": "Un poderoso felino rayado, símbolo de fuerza y belleza en la naturaleza."},
    {"palabra": "Oso", "categoria": "animal", "frase": "Un mamífero corpulento y peludo que habita en diversas regiones del mundo."},
    {"palabra": "Zorro", "categoria": "animal", "frase": "Un astuto mamífero carnívoro conocido por su inteligencia y su distintiva cola peluda."},
    {"palabra": "Lobo", "categoria": "animal", "frase": "Un cazador social que vive en manadas y se destaca por su aullido característico."},
    {"palabra": "Cebra", "categoria": "animal", "frase": "Un equino rayado blanco y negro, nativo de África y símbolo de la sabana."},
    {"palabra": "Jirafa", "categoria": "animal", "frase": "Un mamífero herbívoro de cuello largo, conocido por ser el animal terrestre más alto del mundo."},
    {"palabra": "Rinoceronte", "categoria": "animal", "frase": "Un robusto herbívoro de piel gruesa y uno o varios cuernos en el hocico, que habita en África y Asia."},    
    {"palabra": "Hipopótamo", "categoria": "animal", "frase": "Un mamífero semiacuático de gran tamaño, conocido por su agresividad y sus dientes prominentes."},
    {"palabra": "Cocodrilo", "categoria": "animal", "frase": "Un reptil semiacuático depredador, con una mandíbula poderosa y escamas en su piel."},
    {"palabra": "Serpiente", "categoria": "animal", "frase": "Un reptil sin patas, caracterizado por su cuerpo largo y delgado, y su habilidad para desplazarse reptando."},
    {"palabra": "Tortuga", "categoria": "animal", "frase": "Un reptil de caparazón duro que vive en tierra y agua, capaz de retraer su cabeza y extremidades dentro de su caparazón."},
    {"palabra": "Lagarto", "categoria": "animal", "frase": "Un reptil de cuerpo alargado, con cuatro patas y una cola larga, que suele habitar en zonas cálidas y rocosas."},
    {"palabra": "Camaleón", "categoria": "animal", "frase": "Un reptil conocido por su capacidad para cambiar de color y sus ojos independientes, adaptándose así a su entorno."},
    {"palabra": "Pájaro", "categoria": "animal", "frase": "Un animal vertebrado de sangre caliente, con plumas y alas, que generalmente puede volar."},
    {"palabra": "Águila", "categoria": "animal", "frase": "Un majestuoso ave rapaz, símbolo de poder y libertad, con una vista aguda y garras afiladas."},
    {"palabra": "Búho", "categoria": "animal", "frase": "Un ave nocturna de hábitos cazadores, conocida por sus grandes ojos y su capacidad para girar la cabeza 180 grados."},
    {"palabra": "Cuervo", "categoria": "ave", "frase": "Un ave negra y grande, conocida por su inteligencia y su llamativo canto."},
    {"palabra": "Pingüino", "categoria": "ave", "frase": "Un ave marina no voladora, adaptada para nadar y sumergirse en aguas frías, con un característico plumaje blanco y negro."},
    {"palabra": "Flamenco", "categoria": "ave", "frase": "Un ave zancuda de patas largas y cuello largo, conocida por su plumaje rosa y sus elegantes movimientos."},
    {"palabra": "Colibrí", "categoria": "ave", "frase": "Un pequeño pájaro conocido por su rápido aleteo de alas y su capacidad para libar néctar de las flores."},
    {"palabra": "Avestruz", "categoria": "ave", "frase": "Un ave corredora de gran tamaño, incapaz de volar pero conocida por ser el ave más grande del mundo."},
    {"palabra": "Pavo real", "categoria": "ave", "frase": "Un ave exótica conocida por su deslumbrante plumaje y su capacidad para desplegar un abanico de colores en su cola durante el cortejo."},
    {"palabra": "Canario", "categoria": "ave", "frase": "Un pequeño pájaro cantor, apreciado por su melodioso canto y su plumaje vibrante."},
    {"palabra": "Pato", "categoria": "ave", "frase": "Un ave acuática de tamaño mediano a grande, conocida por su pico ancho y sus habilidades para nadar y bucear."},
    {"palabra": "Ganso", "categoria": "ave", "frase": "Un ave acuática de tamaño grande, reconocida por su cuello largo y su característico graznido."},
    {"palabra": "Cisne", "categoria": "ave", "frase": "Un elegante ave acuática de cuello largo y plumaje blanco, asociada con la belleza y la gracia."},
    {"palabra": "Pelícano", "categoria": "ave", "frase": "Un ave acuática de gran tamaño, con una bolsa debajo del pico para atrapar y almacenar peces."},
    {"palabra": "Pavo", "categoria": "ave", "frase": "Un ave de granja, conocida por su carne sabrosa y su plumaje vistoso, especialmente durante la temporada de Navidad."},
    {"palabra": "Gallo", "categoria": "ave", "frase": "Un macho adulto de la especie de gallina, conocido por su cresta roja y su canto matutino."},
    {"palabra": "Gallina", "categoria": "ave", "frase": "Una hembra adulta de la especie de gallina, criada comúnmente por sus huevos y carne."},
    {"palabra": "Caballo", "categoria": "mamífero", "frase": "Un majestuoso animal de granja y doméstico, conocido por su fuerza, velocidad y su importancia histórica en la civilización humana."},
    {"palabra": "Burro", "categoria": "mamífero", "frase": "Un animal de carga de tamaño mediano, reconocido por sus orejas largas y su temperamento tranquilo."},
    {"palabra": "Cabra", "categoria": "mamífero", "frase": "Un pequeño rumiante doméstico, criado comúnmente por su leche, carne y capacidad para pastar en terrenos difíciles."},
    {"palabra": "Oveja", "categoria": "mamífero", "frase": "Un rumiante doméstico, criado comúnmente por su lana, carne y leche, y conocido por su rebaño social."},
    {"palabra": "Vaca", "categoria": "mamífero", "frase": "Un gran rumiante doméstico, criado comúnmente por su leche, carne y cuero, y conocido por su apacible naturaleza."},
    {"palabra": "Cerdo", "categoria": "mamífero", "frase": "Un mamífero omnívoro de granja, criado comúnmente por su carne, y conocido por su inteligencia y su capacidad para la alimentación de desechos."},
    {"palabra": "Ciervo", "categoria": "animal", "frase": "Un elegante mamífero herbívoro de la familia de los cervidae, conocido por sus astas ramificadas y su grácil apariencia."},    
    {"palabra": "Reno", "categoria": "animal", "frase": "Un mamífero de la familia de los cérvidos adaptado a los climas fríos, conocido por su pelaje denso y sus astas adornadas."},
    {"palabra": "Alce", "categoria": "animal", "frase": "Un mamífero herbívoro de gran tamaño, con astas anchas y un hocico largo, que habita en bosques y regiones montañosas."},
    {"palabra": "Caribú", "categoria": "animal", "frase": "Un tipo de reno que habita principalmente en América del Norte y se destaca por sus grandes migraciones estacionales."},
    {"palabra": "Bisonte", "categoria": "animal", "frase": "Un mamífero herbívoro de gran tamaño, con una cabeza grande y peluda, que solía habitar las llanuras de América del Norte."},
    {"palabra": "Búfalo", "categoria": "animal", "frase": "Un mamífero de la familia de los bóvidos, conocido por su gran tamaño y su distintiva joroba en la parte posterior del cuello."},
    {"palabra": "Antílope", "categoria": "animal", "frase": "Un ágil mamífero herbívoro, conocido por su velocidad y sus cuernos largos y curvados, que habita en las llanuras y praderas."},
    {"palabra": "Ñu", "categoria": "animal", "frase": "Un antílope de tamaño medio, conocido por sus grandes migraciones en África, donde a menudo se convierte en presa de depredadores como los leones."},
    {"palabra": "Lince", "categoria": "animal", "frase": "Un felino de tamaño mediano, conocido por sus orejas puntiagudas y su habilidad para cazar en silencio en áreas boscosas."},
    {"palabra": "Nutria", "categoria": "animal", "frase": "Un mamífero semiacuático de la familia de los mustélidos, conocido por su agilidad en el agua y su pelaje denso y suave."},
    {"palabra": "Armadillo", "categoria": "animal", "frase": "Un mamífero con un caparazón duro y escamas, que se enrolla en una bola para protegerse cuando se siente amenazado."},
    {"palabra": "Topo", "categoria": "animal", "frase": "Un pequeño mamífero subterráneo, conocido por su hocico puntiagudo y sus hábitos de excavación."},
    {"palabra": "Erizo", "categoria": "animal", "frase": "Un pequeño mamífero cubierto de espinas afiladas, que se enrolla en una bola cuando se siente amenazado."},
    {"palabra": "Puercoespín", "categoria": "animal", "frase": "Un mamífero cubierto de espinas largas y puntiagudas, que utiliza para defenderse de los depredadores."},
    {"palabra": "Mapache", "categoria": "animal", "frase": "Un mamífero omnívoro de hábitos nocturnos, conocido por su característica máscara facial y su habilidad para manipular objetos con sus manos."},
    {"palabra": "Hurón", "categoria": "animal", "frase": "Un pequeño mamífero carnívoro de la familia de los mustélidos, a menudo domesticado como mascota o utilizado para cazar roedores en granjas."},
    {"palabra": "Marta", "categoria": "animal", "frase": "Un mamífero carnívoro similar al hurón, conocido por su pelaje suave y su habilidad para cazar presas pequeñas."},
    {"palabra": "Comadreja", "categoria": "animal", "frase": "Un pequeño mamífero carnívoro de la familia de los mustélidos, conocido por su agilidad y su capacidad para cazar presas más grandes que ella misma."},
    {"palabra": "Musaraña", "categoria": "animal", "frase": "Un pequeño mamífero insectívoro, conocido por su metabolismo rápido y su necesidad de alimentarse constantemente para mantenerse con vida."},
    {"palabra": "Ratón", "categoria": "animal", "frase": "Un pequeño roedor de la familia de los murinos, conocido por su capacidad para infestar lugares habitados por humanos y por ser una presa común para muchos depredadores."},
    {"palabra": "Rata", "categoria": "animal", "frase": "Un roedor omnívoro de tamaño pequeño a mediano, conocido por su capacidad de adaptación y su reputación como plaga urbana."},    
    {"palabra": "Ardilla", "categoria": "animal", "frase": "Un pequeño mamífero roedor conocido por su agilidad para trepar árboles y por almacenar comida en sus mejillas."},
    {"palabra": "Castor", "categoria": "animal", "frase": "Un roedor semiacuático conocido por su habilidad para construir represas y madrigueras utilizando troncos y ramas."},
    {"palabra": "Conejo", "categoria": "animal", "frase": "Un pequeño mamífero lagomorfo conocido por sus largas orejas y su reproducción rápida."},
    {"palabra": "Liebre", "categoria": "animal", "frase": "Un mamífero lagomorfo de tamaño mediano, conocido por su velocidad y su capacidad para saltar grandes distancias."},
    {"palabra": "Oso hormiguero", "categoria": "animal", "frase": "Un mamífero insectívoro de América Central y del Sur, con un hocico largo y una lengua pegajosa para atrapar hormigas y termitas."},
    {"palabra": "Canguro", "categoria": "animal", "frase": "Un marsupial herbívoro conocido por su poderoso salto y su bolsa marsupial en la que lleva a sus crías en desarrollo."},
    {"palabra": "Koala", "categoria": "animal", "frase": "Un marsupial arbóreo nativo de Australia, conocido por su dieta de hojas de eucalipto y su aspecto adorable."},
    {"palabra": "Wombat", "categoria": "animal", "frase": "Un marsupial terrestre de Australia, conocido por su cuerpo robusto y su hábito de excavar madrigueras."},
    {"palabra": "Wallaby", "categoria": "animal", "frase": "Un marsupial similar al canguro pero de menor tamaño, que habita en Australia y Nueva Guinea."},
    {"palabra": "Dingo", "categoria": "animal", "frase": "Un cánido salvaje nativo de Australia, conocido por su apariencia similar a la de un perro doméstico y su comportamiento cazador."},
    {"palabra": "Zarigüeya", "categoria": "animal", "frase": "Un marsupial arbóreo de América, conocido por su cola prensil y su habilidad para colgar de las ramas."},
    {"palabra": "Ualabí", "categoria": "animal", "frase": "Un marsupial similar al canguro pero de menor tamaño, que habita en Australia y Nueva Guinea."},
    {"palabra": "Ornitorrinco", "categoria": "animal", "frase": "Un mamífero semiacuático endémico de Australia, conocido por su aspecto peculiar y su capacidad de poner huevos."},
    {"palabra": "Tucán", "categoria": "animal", "frase": "Un ave tropical conocida por su pico grande y colorido, que habita en las selvas de América Central y del Sur."},
    {"palabra": "Loro", "categoria": "animal", "frase": "Un ave conocida por su habilidad para imitar sonidos humanos y su plumaje colorido, que es popular como mascota."},
    {"palabra": "Perico", "categoria": "animal", "frase": "Un tipo de loro de tamaño pequeño a mediano, conocido por su capacidad para aprender trucos y su personalidad juguetona."},
    {"palabra": "Guacamayo", "categoria": "animal", "frase": "Un loro grande y colorido, conocido por su capacidad para hablar y su plumaje brillante."},
    {"palabra": "Cotorra", "categoria": "animal", "frase": "Un tipo de loro de tamaño mediano a pequeño, conocido por su comportamiento ruidoso y su habilidad para imitar sonidos."},
    {"palabra": "Picaflor", "categoria": "ave", "frase": "Un pequeño pájaro conocido por su capacidad de volar en el aire suspendido mientras liba néctar de las flores con su largo pico."},    
    {"palabra": "Cóndor", "categoria": "ave", "frase": "Un ave rapaz de gran tamaño, conocida por su vuelo majestuoso y su papel simbólico en algunas culturas sudamericanas."},
    {"palabra": "Gaviota", "categoria": "ave", "frase": "Un ave marina de tamaño mediano a grande, conocida por su habilidad para volar largas distancias sobre el mar y su graznido distintivo."},
    {"palabra": "Paloma", "categoria": "ave", "frase": "Un ave doméstica de la familia de las Columbidae, conocida por su simbolismo de paz y su capacidad para encontrar el camino a casa desde largas distancias."},
    {"palabra": "Gorrión", "categoria": "ave", "frase": "Un pequeño pájaro comúnmente encontrado en áreas urbanas y rurales, conocido por su plumaje marrón y su canto alegre."},
    {"palabra": "Mirlo", "categoria": "ave", "frase": "Un pájaro cantor de tamaño mediano, conocido por su plumaje negro brillante y su canto melodioso durante la primavera y el verano."},
    {"palabra": "Ruiseñor", "categoria": "ave", "frase": "Un pequeño pájaro conocido por su canto melodioso y su plumaje discreto, que a menudo se asocia con la poesía y la literatura."},
    {"palabra": "Águila pescadora", "categoria": "ave", "frase": "Un águila especializada en la pesca, conocida por su habilidad para atrapar peces del agua con sus garras afiladas mientras vuela sobre lagos y ríos."},
    {"palabra": "Halcón", "categoria": "ave", "frase": "Un ave rapaz de tamaño mediano a grande, conocida por su velocidad en el vuelo y su agudeza visual en la caza."},
    {"palabra": "Buitre", "categoria": "ave", "frase": "Un ave carroñera de gran tamaño, conocida por su papel en la limpieza de cadáveres en el ecosistema y su vuelo en círculos sobre áreas de alimentación potencial."},
    {"palabra": "Codorniz", "categoria": "ave", "frase": "Un ave pequeña de la familia de las Codornizae, conocida por su carne sabrosa y su canto característico."},
    {"palabra": "Ánade", "categoria": "ave", "frase": "Un tipo de pato comúnmente encontrado en lagos, estanques y ríos, conocido por su plumaje colorido y su comportamiento migratorio."},
    {"palabra": "Petirrojo", "categoria": "ave", "frase": "Un pequeño pájaro cantor con un pecho anaranjado distintivo, conocido por su presencia frecuente en jardines y parques durante el invierno."},
    {"palabra": "Colibrí", "categoria": "ave", "frase": "Un pequeño pájaro conocido por su capacidad de volar en el aire suspendido mientras liba néctar de las flores con su largo pico."},
    {"palabra": "Pica", "categoria": "ave", "frase": "Un pequeño pájaro omnívoro de la familia de los corvidos, conocido por su curiosidad y su hábito de recolectar y almacenar objetos brillantes."},
    {"palabra": "Cuervo", "categoria": "ave", "frase": "Un ave negra y grande, conocida por su inteligencia y su llamativo canto."},
    {"palabra": "Urraca", "categoria": "ave", "frase": "Un ave de tamaño mediano de la familia de los corvidos, conocida por su plumaje negro y blanco y su afición por recolectar objetos brillantes."},
    {"palabra": "Alcaudón", "categoria": "ave", "frase": "Un pájaro pequeño y carnívoro, conocido por empalar a sus presas en espinas o alambres de púas antes de consumirlas."},
    {"palabra": "Buitrón", "categoria": "ave", "frase": "Un buitre de menor tamaño en comparación con otras especies, conocido por su función en la limpieza de carrona en los ecosistemas."},
    {"palabra": "Lombriz", "categoria": "animal", "frase": "Un anélido que habita en el suelo y desempeña un papel importante en la fertilización del suelo y la descomposición de la materia orgánica."},
    {"palabra": "Hormiga", "categoria": "insecto", "frase": "Un pequeño insecto social que vive en colonias organizadas, conocido por su trabajo en equipo y su capacidad para transportar objetos mucho más grandes que ellas mismas."},
    {"palabra": "Abeja", "categoria": "insecto", "frase": "Un insecto polinizador que produce miel, conocido por su importancia en la polinización de plantas y su estructura social en colmenas."},
    {"palabra": "Mariposa", "categoria": "insecto", "frase": "Un insecto volador con alas coloridas y delicadas, conocido por su transformación durante el proceso de metamorfosis y su belleza estética."},
    {"palabra": "Mosca", "categoria": "insecto", "frase": "Un insecto volador comúnmente encontrado en entornos urbanos y rurales, conocido por su capacidad para transmitir enfermedades y su rápido ciclo de vida."},
    {"palabra": "Mosquito", "categoria": "insecto", "frase": "Un insecto volador pequeño y zumbador, conocido por su picadura molesta y su papel como vector de enfermedades como la malaria y el dengue."},
    {"palabra": "Araña", "categoria": "artrópodo", "frase": "Un arácnido carnívoro con ocho patas y la capacidad de tejer telarañas para atrapar presas, conocido por su veneno y su amplia diversidad de especies."},
    {"palabra": "Escorpión", "categoria": "artrópodo", "frase": "Un arácnido con una cola curvada y un aguijón venenoso en el extremo, conocido por su picadura dolorosa y su habilidad para cazar presas."},
    {"palabra": "Cienpiés", "categoria": "artrópodo", "frase": "Un artrópodo terrestre con muchas patas segmentadas, conocido por su aspecto peculiar y su hábito de vivir en lugares oscuros y húmedos."},
    {"palabra": "Chinche", "categoria": "insecto", "frase": "Un pequeño insecto con cuerpo aplanado, conocido por su picadura dolorosa y su capacidad para infestar hogares y hoteles."},
    {"palabra": "Libélula", "categoria": "insecto", "frase": "Un insecto volador grande y delicado, conocido por sus alas transparentes y su capacidad para cazar otros insectos en vuelo."},
    {"palabra": "Grillo", "categoria": "insecto", "frase": "Un insecto saltamontes conocido por su canto nocturno y su habilidad para saltar largas distancias."},
    {"palabra": "Saltamontes", "categoria": "insecto", "frase": "Un insecto herbívoro con patas traseras desarrolladas para saltar, conocido por su capacidad de camuflarse en su entorno y su papel en la cadena alimentaria."},
    {"palabra": "Langosta", "categoria": "insecto", "frase": "Un insecto relacionado con los saltamontes, conocido por su capacidad para formar enjambres y causar daños a los cultivos en áreas agrícolas."},
    {"palabra": "Cucaracha", "categoria": "insecto", "frase": "Un insecto nocturno y resistente que se encuentra comúnmente en entornos urbanos, conocido por su capacidad para sobrevivir en condiciones adversas y su asociación con la suciedad."},
    {"palabra": "Ciempies", "categoria": "artrópodo", "frase": "Un artrópodo terrestre con numerosas patas segmentadas, conocido por su apariencia intimidante y su función en la descomposición de materia orgánica en el suelo."},
    {"palabra": "Centollo", "categoria": "crustáceo", "frase": "Un crustáceo marino de caparazón duro y patas largas, conocido por su carne sabrosa y su uso en la cocina como marisco."},
    {"palabra": "Cangrejo", "categoria": "crustáceo", "frase": "Un crustáceo marino o de agua dulce con un caparazón quitinoso y pinzas, conocido por su amplia variedad de especies y su importancia en la cadena alimentaria."},
    {"palabra": "Langosta", "categoria": "crustáceo", "frase": "Un crustáceo marino con un caparazón duro y antenas largas, conocido por su carne delicada y su valor culinario en platos gourmet."},
    {"palabra": "Camarón", "categoria": "crustáceo", "frase": "Un crustáceo marino o de agua dulce con un cuerpo alargado y patas adaptadas para nadar, conocido por su carne tierna y su popularidad como marisco."},
    {"palabra": "Pulpo", "categoria": "molusco", "frase": "Un molusco marino con ocho tentáculos y una habilidad excepcional para cambiar de color y camuflarse en su entorno, conocido por su inteligencia y su sabor delicado en la cocina."}
]